[package]
name = "pollux_console"
version = "0.1.0"
license = "BSD-3"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6"
crossterm = "0.28.1"
get_if_addrs = "0.5.3"
ratatui = "0.29.0"
<<<<<<< HEAD
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1"
=======
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"

>>>>>>> a44460c13cd3186624d16190d6a401976ae7cfb2
